/**
 * 小惠食物数据库
 * 针对 UCTD / 狼疮倾向 患者的饮食指南
 *
 * safety: 'good' = 推荐  |  'ok' = 适量  |  'caution' = 少吃  |  'avoid' = 避免
 * category: 食物分类
 *
 * 数据来源：基于风湿科医学文献、狼疮饮食指南、地中海饮食研究整理
 * 最后更新：2026-03
 */

export interface FoodItem {
  name: string;        // 中文名
  alias?: string[];    // 别名/拼音/英文，用于搜索
  emoji: string;
  category: string;
  safety: 'good' | 'ok' | 'caution' | 'avoid';
  reason: string;      // 为什么推荐/限制
  tip?: string;        // 额外小贴士
}

export const FOOD_DATABASE: FoodItem[] = [
  // ==================== 蔬菜 (50+) ====================
  { name: '西兰花', alias: ['花椰菜','broccoli','xilan','xilanhua'], emoji: '🥦', category: '蔬菜', safety: 'good', reason: '十字花科蔬菜，抗炎抗氧化', tip: '蒸或轻炒保留营养' },
  { name: '菠菜', alias: ['spinach','bocai'], emoji: '🥬', category: '蔬菜', safety: 'good', reason: '富含叶酸、铁、维生素K，抗炎' },
  { name: '羽衣甘蓝', alias: ['kale','yuyi','yuyiganlan'], emoji: '🥬', category: '蔬菜', safety: 'good', reason: '超级蔬菜，抗氧化能力强' },
  { name: '胡萝卜', alias: ['carrot','huluobo'], emoji: '🥕', category: '蔬菜', safety: 'good', reason: '富含β-胡萝卜素，保护皮肤' },
  { name: '白菜', alias: ['大白菜','Chinese cabbage','baicai','dabai'], emoji: '🥬', category: '蔬菜', safety: 'good', reason: '温和易消化，维生素C丰富' },
  { name: '小白菜', alias: ['青菜','oil greens','xiaobaicai','qingcai'], emoji: '🥬', category: '蔬菜', safety: 'good', reason: '钙含量高，日常好蔬菜' },
  { name: '黄瓜', alias: ['cucumber','huanggua'], emoji: '🥒', category: '蔬菜', safety: 'good', reason: '清热补水，低热量' },
  { name: '芹菜', alias: ['celery','qincai'], emoji: '🥬', category: '蔬菜', safety: 'good', reason: '含芹菜素，有一定抗炎作用' },
  { name: '南瓜', alias: ['pumpkin','nangua'], emoji: '🎃', category: '蔬菜', safety: 'good', reason: '富含维A和纤维，温和易消化' },
  { name: '红薯', alias: ['地瓜','番薯','sweet potato','hongshu','digua'], emoji: '🍠', category: '蔬菜', safety: 'good', reason: '复合碳水+抗氧化物，稳定血糖' },
  { name: '西葫芦', alias: ['zucchini','xihulu'], emoji: '🥒', category: '蔬菜', safety: 'good', reason: '低热量高纤维，温和不刺激' },
  { name: '丝瓜', alias: ['sigua','luffa'], emoji: '🥒', category: '蔬菜', safety: 'good', reason: '清热利湿，适合日常食用' },
  { name: '莲藕', alias: ['lotus root','liannou','ou'], emoji: '🪷', category: '蔬菜', safety: 'good', reason: '健脾养胃，营养丰富' },
  { name: '山药', alias: ['shanyao','yam','huaishanyao'], emoji: '🥔', category: '蔬菜', safety: 'good', reason: '补脾益肺，温和滋养' },
  { name: '冬瓜', alias: ['donggua','winter melon'], emoji: '🍈', category: '蔬菜', safety: 'good', reason: '利尿消肿，清热' },
  { name: '苦瓜', alias: ['bitter melon','kugua'], emoji: '🥒', category: '蔬菜', safety: 'good', reason: '清热降火，含抗炎成分', tip: '口感苦但对身体有益' },
  { name: '生菜', alias: ['lettuce','shengcai'], emoji: '🥬', category: '蔬菜', safety: 'good', reason: '低热量高水分，维生素丰富' },
  { name: '油麦菜', alias: ['youmaicai','lettuce'], emoji: '🥬', category: '蔬菜', safety: 'good', reason: '清脆可口，营养好' },
  { name: '空心菜', alias: ['通心菜','kangkong','kongxincai'], emoji: '🥬', category: '蔬菜', safety: 'good', reason: '富含铁和膳食纤维' },
  { name: '韭菜', alias: ['chive','jiucai'], emoji: '🌿', category: '蔬菜', safety: 'ok', reason: '温热性蔬菜，适量食用', tip: '消化不好时少吃' },
  { name: '芦笋', alias: ['asparagus','lusun'], emoji: '🌿', category: '蔬菜', safety: 'good', reason: '抗炎+含谷胱甘肽，保护细胞' },
  { name: '花菜', alias: ['菜花','cauliflower','huacai'], emoji: '🥦', category: '蔬菜', safety: 'good', reason: '十字花科，抗炎抗氧化' },
  { name: '娃娃菜', alias: ['baby cabbage','wawacai'], emoji: '🥬', category: '蔬菜', safety: 'good', reason: '嫩白菜，易消化，适合煮汤' },
  { name: '紫甘蓝', alias: ['紫包菜','red cabbage','ziganlan'], emoji: '🥬', category: '蔬菜', safety: 'good', reason: '花青素丰富，强抗氧化' },
  { name: '西洋菜', alias: ['watercress','xiyangcai'], emoji: '🌿', category: '蔬菜', safety: 'good', reason: '维C和钙含量高' },
  { name: '茼蒿', alias: ['crown daisy','tonghao'], emoji: '🌿', category: '蔬菜', safety: 'good', reason: '清香蔬菜，富含胡萝卜素' },
  { name: '荠菜', alias: ['shepherd purse','jicai'], emoji: '🌿', category: '蔬菜', safety: 'good', reason: '富含钙和维C，春天时令菜' },
  { name: '秋葵', alias: ['okra','qiukui'], emoji: '🌿', category: '蔬菜', safety: 'good', reason: '含黏液蛋白保护胃黏膜，低热量' },
  { name: '竹笋', alias: ['bamboo shoot','zhusun'], emoji: '🎍', category: '蔬菜', safety: 'ok', reason: '高纤维低热量，但偏寒凉', tip: '消化弱的时候少吃' },
  { name: '豌豆', alias: ['pea','wandou'], emoji: '🫛', category: '蔬菜', safety: 'good', reason: '蛋白质和纤维丰富' },
  { name: '四季豆', alias: ['green bean','sijidou','豆角'], emoji: '🫛', category: '蔬菜', safety: 'good', reason: '高蛋白蔬菜', tip: '一定要煮熟，生的有毒' },
  { name: '番茄', alias: ['西红柿','tomato','fanqie','xihongshi'], emoji: '🍅', category: '蔬菜', safety: 'ok', reason: '茄科蔬菜，部分患者可能敏感', tip: '观察吃后反应，煮熟比生吃好' },
  { name: '茄子', alias: ['eggplant','qiezi'], emoji: '🍆', category: '蔬菜', safety: 'ok', reason: '茄科蔬菜，因人而异', tip: '如果吃后关节不适建议减少' },
  { name: '青椒', alias: ['辣椒','pepper','qingjiao','lajiao'], emoji: '🫑', category: '蔬菜', safety: 'ok', reason: '茄科蔬菜，少量可以', tip: '辣椒素有一定抗炎作用但可能刺激肠胃' },
  { name: '土豆', alias: ['马铃薯','potato','tudou'], emoji: '🥔', category: '蔬菜', safety: 'ok', reason: '茄科蔬菜，大多数人可以正常吃', tip: '发芽的土豆不要吃' },
  { name: '芋头', alias: ['taro','yutou'], emoji: '🥔', category: '蔬菜', safety: 'good', reason: '易消化淀粉，温和补益' },
  { name: '百合', alias: ['lily bulb','baihe'], emoji: '🌸', category: '蔬菜', safety: 'good', reason: '润肺清心，适合炒菜或煮汤' },
  { name: '紫薯', alias: ['purple sweet potato','zishu'], emoji: '🍠', category: '蔬菜', safety: 'good', reason: '花青素+膳食纤维，抗氧化' },
  { name: '莴笋', alias: ['lettuce stem','wosun'], emoji: '🥒', category: '蔬菜', safety: 'good', reason: '富含钾，清热利尿' },
  { name: '豆苗', alias: ['pea shoot','doumiao'], emoji: '🌱', category: '蔬菜', safety: 'good', reason: '嫩豌豆苗，维C丰富' },
  { name: '苜蓿', alias: ['苜蓿芽','alfalfa','muxu','alfalfa sprouts'], emoji: '🌱', category: '蔬菜', safety: 'avoid', reason: '含L-刀豆氨酸，可直接触发狼疮症状！', tip: '这是最重要的饮食禁忌，任何含苜蓿的食品都要避免' },
  { name: '大蒜', alias: ['garlic','dasuan','蒜'], emoji: '🧄', category: '蔬菜', safety: 'ok', reason: '有免疫增强作用，少量调味可以', tip: '做菜放几瓣没问题，不建议大量生吃' },
  { name: '洋葱', alias: ['onion','yangcong'], emoji: '🧅', category: '蔬菜', safety: 'good', reason: '含槲皮素，有一定抗炎效果' },
  { name: '生姜', alias: ['姜','ginger','shengjiang'], emoji: '🫚', category: '蔬菜', safety: 'good', reason: '天然抗炎，缓解恶心' },
  { name: '蘑菇', alias: ['香菇','mushroom','mogu','xianggu'], emoji: '🍄', category: '蔬菜', safety: 'good', reason: '富含维生素D和多糖，增强免疫' },
  { name: '木耳', alias: ['黑木耳','muer','black fungus'], emoji: '🍄', category: '蔬菜', safety: 'good', reason: '补铁活血，膳食纤维丰富' },
  { name: '银耳', alias: ['white fungus','yiner'], emoji: '🍄', category: '蔬菜', safety: 'good', reason: '润肺养颜，适合煮羹' },
  { name: '金针菇', alias: ['enoki','jinzhengu'], emoji: '🍄', category: '蔬菜', safety: 'good', reason: '高蛋白低脂肪，膳食纤维丰富' },
  { name: '平菇', alias: ['oyster mushroom','pinggu'], emoji: '🍄', category: '蔬菜', safety: 'good', reason: '营养好价格便宜的菌类' },
  { name: '杏鲍菇', alias: ['king oyster','xingbaogu'], emoji: '🍄', category: '蔬菜', safety: 'good', reason: '口感好，蛋白质含量高' },
  { name: '豆芽', alias: ['bean sprout','douya','黄豆芽','绿豆芽'], emoji: '🌱', category: '蔬菜', safety: 'good', reason: '黄豆芽/绿豆芽都可以，注意不是苜蓿芽' },
  { name: '葱', alias: ['scallion','cong','大葱','小葱'], emoji: '🌿', category: '蔬菜', safety: 'good', reason: '日常调味蔬菜，含硫化物抗炎' },
  { name: '萝卜', alias: ['白萝卜','radish','luobo'], emoji: '🥬', category: '蔬菜', safety: 'good', reason: '通气消食，冬天好蔬菜' },
  { name: '红萝卜', alias: ['甜菜根','beet','beetroot','tiancaigen'], emoji: '🥕', category: '蔬菜', safety: 'good', reason: '甜菜碱有抗炎作用' },
  { name: '香菜', alias: ['芫荽','cilantro','xiangcai'], emoji: '🌿', category: '蔬菜', safety: 'good', reason: '富含维C和维K，可以正常吃' },

  // ==================== 水果 (40+) ====================
  { name: '蓝莓', alias: ['blueberry','lanmei'], emoji: '🫐', category: '水果', safety: 'good', reason: '抗氧化之王，花青素丰富' },
  { name: '樱桃', alias: ['cherry','yingtao'], emoji: '🍒', category: '水果', safety: 'good', reason: '抗炎+抗氧化，适量食用' },
  { name: '苹果', alias: ['apple','pingguo'], emoji: '🍎', category: '水果', safety: 'good', reason: '温和水果，富含纤维和维C' },
  { name: '橙子', alias: ['柑橘','orange','chengzi'], emoji: '🍊', category: '水果', safety: 'good', reason: '维生素C丰富，增强免疫' },
  { name: '猕猴桃', alias: ['奇异果','kiwi','mihoutao'], emoji: '🥝', category: '水果', safety: 'good', reason: '维C含量极高，抗氧化' },
  { name: '香蕉', alias: ['banana','xiangjiao'], emoji: '🍌', category: '水果', safety: 'good', reason: '富含钾，缓解肌肉紧张' },
  { name: '葡萄', alias: ['grape','putao'], emoji: '🍇', category: '水果', safety: 'good', reason: '含白藜芦醇，抗炎抗氧化' },
  { name: '草莓', alias: ['strawberry','caomei'], emoji: '🍓', category: '水果', safety: 'good', reason: '富含维C和花青素' },
  { name: '西瓜', alias: ['watermelon','xigua'], emoji: '🍉', category: '水果', safety: 'ok', reason: '补水解暑，但含糖较高', tip: '适量吃，不要当饭吃' },
  { name: '芒果', alias: ['mango','mangguo'], emoji: '🥭', category: '水果', safety: 'ok', reason: '营养丰富但部分人可能过敏', tip: '如果从未过敏可以正常吃' },
  { name: '牛油果', alias: ['鳄梨','avocado','niuyouguo'], emoji: '🥑', category: '水果', safety: 'good', reason: '富含好脂肪和维生素E，抗炎' },
  { name: '柠檬', alias: ['lemon','ningmeng'], emoji: '🍋', category: '水果', safety: 'good', reason: '维C丰富，泡水喝很好' },
  { name: '梨', alias: ['pear','li','雪梨','鸭梨'], emoji: '🍐', category: '水果', safety: 'good', reason: '润肺止咳，温和水果' },
  { name: '石榴', alias: ['pomegranate','shiliu'], emoji: '🫐', category: '水果', safety: 'good', reason: '抗氧化能力很强' },
  { name: '火龙果', alias: ['dragon fruit','huolongguo'], emoji: '🐉', category: '水果', safety: 'good', reason: '富含纤维和抗氧化物' },
  { name: '木瓜', alias: ['papaya','mugua'], emoji: '🍈', category: '水果', safety: 'good', reason: '含木瓜蛋白酶，助消化抗炎' },
  { name: '桃子', alias: ['peach','taozi','水蜜桃'], emoji: '🍑', category: '水果', safety: 'good', reason: '维C和纤维丰富，夏季好水果' },
  { name: '李子', alias: ['plum','lizi'], emoji: '🫐', category: '水果', safety: 'ok', reason: '含有机酸和花青素', tip: '不要空腹多吃，容易伤胃' },
  { name: '杏', alias: ['apricot','xing'], emoji: '🍑', category: '水果', safety: 'ok', reason: '富含维A，适量食用' },
  { name: '山楂', alias: ['hawthorn','shanzha'], emoji: '🔴', category: '水果', safety: 'ok', reason: '助消化开胃，含有机酸' },
  { name: '柚子', alias: ['grapefruit','youzi','西柚'], emoji: '🍊', category: '水果', safety: 'ok', reason: '维C丰富，但可能与某些药物相互作用', tip: '如果同时吃其他药物，先咨询医生' },
  { name: '哈密瓜', alias: ['cantaloupe','hamigua'], emoji: '🍈', category: '水果', safety: 'good', reason: '富含维A和维C' },
  { name: '甜瓜', alias: ['melon','tiangua','香瓜'], emoji: '🍈', category: '水果', safety: 'good', reason: '清甜补水，夏天好水果' },
  { name: '荔枝', alias: ['lychee','lizhi'], emoji: '🫐', category: '水果', safety: 'ok', reason: '含糖量高，容易上火', tip: '每次不超过10颗' },
  { name: '龙眼', alias: ['桂圆','longan','longyan','guiyuan'], emoji: '🫐', category: '水果', safety: 'ok', reason: '温补水果，含糖较高', tip: '适量食用' },
  { name: '菠萝', alias: ['凤梨','pineapple','boluo'], emoji: '🍍', category: '水果', safety: 'ok', reason: '含菠萝蛋白酶有一定抗炎作用', tip: '部分人可能口腔过敏，盐水泡一下' },
  { name: '椰子', alias: ['coconut','yezi'], emoji: '🥥', category: '水果', safety: 'good', reason: '电解质丰富，椰子水补水好' },
  { name: '榴莲', alias: ['durian','liulian'], emoji: '🍈', category: '水果', safety: 'ok', reason: '热量高但营养丰富', tip: '热性水果，一次不要吃太多' },
  { name: '百香果', alias: ['passion fruit','baixiangguo'], emoji: '🍈', category: '水果', safety: 'good', reason: '维C极高，抗氧化' },
  { name: '无花果', alias: ['fig','wuhuaguo'], emoji: '🫐', category: '水果', safety: 'good', reason: '含钙和纤维，助消化' },
  { name: '柿子', alias: ['persimmon','shizi'], emoji: '🍊', category: '水果', safety: 'ok', reason: '含鞣酸，不宜空腹吃', tip: '不要和高蛋白食物同时大量吃' },
  { name: '杨梅', alias: ['bayberry','yangmei'], emoji: '🫐', category: '水果', safety: 'ok', reason: '含花青素，味酸开胃', tip: '多吃容易牙酸' },
  { name: '枇杷', alias: ['loquat','pipa'], emoji: '🍊', category: '水果', safety: 'good', reason: '润肺止咳，温和水果' },
  { name: '桑葚', alias: ['mulberry','sangshen'], emoji: '🫐', category: '水果', safety: 'good', reason: '花青素丰富，补血养肝' },

  // ==================== 肉类蛋白 (30+) ====================
  { name: '三文鱼', alias: ['鲑鱼','salmon','sanwenyu'], emoji: '🐟', category: '肉蛋', safety: 'good', reason: 'Omega-3 含量最高的鱼，强效抗炎' },
  { name: '鲭鱼', alias: ['mackerel','qingyu'], emoji: '🐟', category: '肉蛋', safety: 'good', reason: '富含Omega-3，价格比三文鱼亲民' },
  { name: '沙丁鱼', alias: ['sardine','shadingyu'], emoji: '🐟', category: '肉蛋', safety: 'good', reason: 'Omega-3+钙+维D，小鱼重金属少' },
  { name: '鸡胸肉', alias: ['鸡肉','chicken','jixiong','ji'], emoji: '🍗', category: '肉蛋', safety: 'good', reason: '优质低脂蛋白质' },
  { name: '鸡蛋', alias: ['egg','jidan'], emoji: '🥚', category: '肉蛋', safety: 'good', reason: '全营养食品，维D来源', tip: '每天1-2个完全没问题' },
  { name: '虾', alias: ['shrimp','xia','虾仁'], emoji: '🦐', category: '肉蛋', safety: 'ok', reason: '优质蛋白，但部分人过敏', tip: '如果不过敏可以正常吃' },
  { name: '牛肉', alias: ['beef','niurou'], emoji: '🥩', category: '肉蛋', safety: 'ok', reason: '补铁补锌，适量吃', tip: '选瘦牛肉，红肉每周2-3次为宜' },
  { name: '猪肉', alias: ['pork','zhurou'], emoji: '🥩', category: '肉蛋', safety: 'ok', reason: '日常肉类，选瘦的', tip: '避免肥肉和五花肉' },
  { name: '猪肝', alias: ['pork liver','zhugan'], emoji: '🥩', category: '肉蛋', safety: 'ok', reason: '补铁效果好，但胆固醇高', tip: '每周不超过1-2次' },
  { name: '羊肉', alias: ['lamb','yangrou'], emoji: '🍖', category: '肉蛋', safety: 'ok', reason: '温补，冬天可以适量吃', tip: '不要吃太多，红肉总量控制' },
  { name: '鸭肉', alias: ['duck','yarou'], emoji: '🦆', category: '肉蛋', safety: 'ok', reason: '比较温和的肉类' },
  { name: '鹅肉', alias: ['goose','erou'], emoji: '🦆', category: '肉蛋', safety: 'ok', reason: '优质蛋白，适量食用' },
  { name: '带鱼', alias: ['hairtail','daiyu'], emoji: '🐟', category: '肉蛋', safety: 'good', reason: '含Omega-3和维A' },
  { name: '鲈鱼', alias: ['sea bass','luyu'], emoji: '🐟', category: '肉蛋', safety: 'good', reason: '高蛋白低脂肪' },
  { name: '鳕鱼', alias: ['cod','xueyu'], emoji: '🐟', category: '肉蛋', safety: 'good', reason: '低脂高蛋白，温和鱼类' },
  { name: '黄花鱼', alias: ['yellow croaker','huanghuayu'], emoji: '🐟', category: '肉蛋', safety: 'good', reason: '肉嫩易消化，钙含量高' },
  { name: '鲫鱼', alias: ['crucian carp','jiyu'], emoji: '🐟', category: '肉蛋', safety: 'good', reason: '适合煲汤，蛋白质丰富' },
  { name: '草鱼', alias: ['grass carp','caoyu'], emoji: '🐟', category: '肉蛋', safety: 'good', reason: '日常淡水鱼，营养好' },
  { name: '鲤鱼', alias: ['carp','liyu'], emoji: '🐟', category: '肉蛋', safety: 'good', reason: '利水消肿' },
  { name: '金枪鱼', alias: ['tuna','jinqiangyu','吞拿鱼'], emoji: '🐟', category: '肉蛋', safety: 'ok', reason: '富含蛋白质和Omega-3', tip: '大型鱼类，注意重金属积累，每周1-2次' },
  { name: '螃蟹', alias: ['crab','pangxie'], emoji: '🦀', category: '肉蛋', safety: 'ok', reason: '高蛋白但偏寒凉', tip: '过敏体质注意，配姜醋食用' },
  { name: '蛤蜊', alias: ['clam','geli','花蛤'], emoji: '🐚', category: '肉蛋', safety: 'ok', reason: '富含铁和锌' },
  { name: '扇贝', alias: ['scallop','shanbei'], emoji: '🐚', category: '肉蛋', safety: 'ok', reason: '低脂高蛋白' },
  { name: '牡蛎', alias: ['生蚝','oyster','muli'], emoji: '🦪', category: '肉蛋', safety: 'ok', reason: '锌含量极高', tip: '一定要吃新鲜熟的' },
  { name: '鱿鱼', alias: ['squid','youyu'], emoji: '🦑', category: '肉蛋', safety: 'ok', reason: '高蛋白，胆固醇偏高' },
  { name: '鸽子', alias: ['pigeon','gezi','乳鸽'], emoji: '🐦', category: '肉蛋', safety: 'ok', reason: '温补肉类，适合煲汤' },
  { name: '鹌鹑蛋', alias: ['quail egg','anchundan'], emoji: '🥚', category: '肉蛋', safety: 'good', reason: '营养比鸡蛋更浓缩' },
  { name: '加工肉类', alias: ['香肠','腊肉','培根','火腿','processed meat','xiangchang','larou','peigen','huotui'], emoji: '🥓', category: '肉蛋', safety: 'caution', reason: '含亚硝酸盐和高盐，促进炎症', tip: '尽量少吃，偶尔吃一次影响不大' },
  { name: '午餐肉', alias: ['spam','wucanrou'], emoji: '🥫', category: '肉蛋', safety: 'caution', reason: '加工肉，高盐高脂肪' },
  { name: '鱼丸', alias: ['fish ball','yuwan'], emoji: '🐟', category: '肉蛋', safety: 'ok', reason: '加工食品，淀粉较多', tip: '火锅配菜偶尔吃' },

  // ==================== 谷物主食 (25+) ====================
  { name: '糙米', alias: ['brown rice','caomi'], emoji: '🍚', category: '主食', safety: 'good', reason: '全谷物，GI低，纤维丰富' },
  { name: '燕麦', alias: ['oat','yanmai','麦片'], emoji: '🥣', category: '主食', safety: 'good', reason: '降胆固醇，β-葡聚糖抗炎' },
  { name: '全麦面包', alias: ['whole wheat bread','quanmai'], emoji: '🍞', category: '主食', safety: 'good', reason: '全谷物，比白面包好很多' },
  { name: '白米饭', alias: ['米饭','rice','mifan','大米'], emoji: '🍚', category: '主食', safety: 'ok', reason: '日常主食，可以吃', tip: '可以掺一些糙米或杂粮' },
  { name: '面条', alias: ['noodle','miantiao','挂面'], emoji: '🍜', category: '主食', safety: 'ok', reason: '普通面条没问题', tip: '有条件选全麦面条' },
  { name: '小米', alias: ['millet','xiaomi','小米粥'], emoji: '🌾', category: '主食', safety: 'good', reason: '养胃暖胃，富含B族维生素' },
  { name: '玉米', alias: ['corn','yumi'], emoji: '🌽', category: '主食', safety: 'good', reason: '富含纤维和叶黄素' },
  { name: '荞麦', alias: ['buckwheat','qiaomai'], emoji: '🌾', category: '主食', safety: 'good', reason: '无麸质杂粮，营养丰富' },
  { name: '藜麦', alias: ['quinoa','limai'], emoji: '🌾', category: '主食', safety: 'good', reason: '超级谷物，完全蛋白质' },
  { name: '紫米', alias: ['purple rice','zimi','黑米'], emoji: '🍚', category: '主食', safety: 'good', reason: '花青素+铁，比白米营养更好' },
  { name: '薏米', alias: ['coix seed','yimi','薏仁'], emoji: '🌾', category: '主食', safety: 'good', reason: '祛湿利水，适合煮粥' },
  { name: '高粱', alias: ['sorghum','gaoliang'], emoji: '🌾', category: '主食', safety: 'good', reason: '无麸质杂粮，营养丰富' },
  { name: '面包', alias: ['bread','mianbao'], emoji: '🍞', category: '主食', safety: 'ok', reason: '白面包GI偏高', tip: '尽量选全麦面包' },
  { name: '馒头', alias: ['steamed bun','mantou'], emoji: '🍞', category: '主食', safety: 'ok', reason: '日常主食，比油条健康' },
  { name: '包子', alias: ['steamed stuffed bun','baozi'], emoji: '🥟', category: '主食', safety: 'ok', reason: '日常主食，选蔬菜馅更好' },
  { name: '饺子', alias: ['dumpling','jiaozi'], emoji: '🥟', category: '主食', safety: 'ok', reason: '营养较全面的主食', tip: '自己包的比速冻的好' },
  { name: '粽子', alias: ['zongzi','rice dumpling'], emoji: '🍚', category: '主食', safety: 'ok', reason: '糯米不易消化', tip: '一次不要吃太多' },
  { name: '年糕', alias: ['rice cake','niangao'], emoji: '🍚', category: '主食', safety: 'ok', reason: '糯米制品，不易消化' },
  { name: '红薯粉', alias: ['sweet potato noodle','hongshuyfen','粉丝','粉条'], emoji: '🍜', category: '主食', safety: 'ok', reason: '淀粉制品，热量不低' },
  { name: '方便面', alias: ['泡面','instant noodle','fangbianmian'], emoji: '🍜', category: '主食', safety: 'caution', reason: '高盐高油，营养单一', tip: '偶尔吃解馋可以，不要经常吃' },
  { name: '油条', alias: ['fried dough stick','youtiao'], emoji: '🥖', category: '主食', safety: 'caution', reason: '高温油炸，含铝', tip: '偶尔吃一根无妨' },
  { name: '麻花', alias: ['fried dough twist','mahua'], emoji: '🥖', category: '主食', safety: 'caution', reason: '油炸食品，高热量' },
  { name: '烧饼', alias: ['sesame flatbread','shaobing'], emoji: '🥖', category: '主食', safety: 'ok', reason: '比油条好一些，但油也不少' },

  // ==================== 豆类 (15+) ====================
  { name: '豆腐', alias: ['tofu','doufu'], emoji: '🧈', category: '豆类', safety: 'good', reason: '优质植物蛋白，钙丰富' },
  { name: '黑豆', alias: ['black bean','heidou'], emoji: '🫘', category: '豆类', safety: 'good', reason: '花青素+植物蛋白' },
  { name: '鹰嘴豆', alias: ['chickpea','yingzuidou'], emoji: '🫘', category: '豆类', safety: 'good', reason: '高蛋白高纤维，地中海饮食常用' },
  { name: '红豆', alias: ['赤豆','red bean','hongdou'], emoji: '🫘', category: '豆类', safety: 'good', reason: '补铁利湿' },
  { name: '绿豆', alias: ['mung bean','lvdou'], emoji: '🫘', category: '豆类', safety: 'good', reason: '清热解毒' },
  { name: '黄豆', alias: ['大豆','soybean','huangdou'], emoji: '🫘', category: '豆类', safety: 'ok', reason: '含植物雌激素，适量吃', tip: '每天适量豆制品没问题，不需要刻意回避' },
  { name: '豆浆', alias: ['soy milk','doujiang'], emoji: '🥛', category: '豆类', safety: 'ok', reason: '同黄豆，适量饮用即可' },
  { name: '毛豆', alias: ['edamame','maodou'], emoji: '🫛', category: '豆类', safety: 'good', reason: '高蛋白低脂，好零食' },
  { name: '腐竹', alias: ['bean curd stick','fuzhu'], emoji: '🧈', category: '豆类', safety: 'ok', reason: '豆制品，蛋白质浓缩' },
  { name: '豆腐干', alias: ['dried tofu','doufugan','豆干'], emoji: '🧈', category: '豆类', safety: 'ok', reason: '豆制品，钙含量高' },
  { name: '豆腐皮', alias: ['tofu skin','doufupi'], emoji: '🧈', category: '豆类', safety: 'ok', reason: '豆制品，蛋白质丰富' },
  { name: '豆腐脑', alias: ['tofu pudding','doufunao','豆花'], emoji: '🥛', category: '豆类', safety: 'ok', reason: '温和豆制品，早餐好选择' },
  { name: '扁豆', alias: ['lentil','biandou'], emoji: '🫘', category: '豆类', safety: 'good', reason: '高纤维高蛋白，铁含量好' },
  { name: '蚕豆', alias: ['broad bean','candou'], emoji: '🫘', category: '豆类', safety: 'ok', reason: '蛋白质丰富，少数人有蚕豆病' },
  { name: '纳豆', alias: ['natto','nadou'], emoji: '🫘', category: '豆类', safety: 'good', reason: '发酵豆制品，含纳豆激酶' },

  // ==================== 乳制品 (10+) ====================
  { name: '牛奶', alias: ['milk','niunai'], emoji: '🥛', category: '乳制品', safety: 'good', reason: '补钙护骨，羟氯喹最好随牛奶服用', tip: '吃药时搭配牛奶效果更好' },
  { name: '酸奶', alias: ['yogurt','suannai'], emoji: '🥛', category: '乳制品', safety: 'good', reason: '补钙+益生菌，保护肠道' },
  { name: '奶酪', alias: ['芝士','cheese','nailao'], emoji: '🧀', category: '乳制品', safety: 'ok', reason: '高钙但也高脂高盐', tip: '选低脂奶酪，每次少量' },
  { name: '鲜奶', alias: ['fresh milk','xiannai','巴氏奶'], emoji: '🥛', category: '乳制品', safety: 'good', reason: '营养保存最好的奶' },
  { name: '羊奶', alias: ['goat milk','yangnai'], emoji: '🥛', category: '乳制品', safety: 'good', reason: '比牛奶更易消化，营养丰富' },
  { name: '脱脂牛奶', alias: ['skim milk','tuozhi'], emoji: '🥛', category: '乳制品', safety: 'good', reason: '低脂补钙好选择' },
  { name: '奶油', alias: ['cream','naiyou'], emoji: '🥛', category: '乳制品', safety: 'caution', reason: '高脂肪，饱和脂肪多' },
  { name: '炼乳', alias: ['condensed milk','lianru'], emoji: '🥛', category: '乳制品', safety: 'caution', reason: '高糖高脂' },
  { name: '乳酸菌饮料', alias: ['yakult','养乐多','rusuanjun'], emoji: '🥛', category: '乳制品', safety: 'ok', reason: '含益生菌但糖分很高', tip: '不如直接喝酸奶' },

  // ==================== 坚果 (15+) ====================
  { name: '核桃', alias: ['walnut','hetao'], emoji: '🥜', category: '坚果', safety: 'good', reason: '富含Omega-3和维E，脑健康' },
  { name: '杏仁', alias: ['almond','xingren'], emoji: '🥜', category: '坚果', safety: 'good', reason: '维E+钙+好脂肪' },
  { name: '腰果', alias: ['cashew','yaoguo'], emoji: '🥜', category: '坚果', safety: 'good', reason: '富含锌和镁' },
  { name: '花生', alias: ['peanut','huasheng'], emoji: '🥜', category: '坚果', safety: 'ok', reason: '营养但属于高过敏原食物', tip: '不过敏就可以正常吃' },
  { name: '开心果', alias: ['pistachio','kaixinguo'], emoji: '🥜', category: '坚果', safety: 'good', reason: '抗氧化+纤维' },
  { name: '亚麻籽', alias: ['flaxseed','yamazi'], emoji: '🌰', category: '坚果', safety: 'good', reason: 'Omega-3植物来源之王', tip: '磨碎了吃吸收更好' },
  { name: '奇亚籽', alias: ['chia seed','qiyazi'], emoji: '🌰', category: '坚果', safety: 'good', reason: 'Omega-3+纤维+蛋白' },
  { name: '松子', alias: ['pine nut','songzi'], emoji: '🥜', category: '坚果', safety: 'good', reason: '富含维E和不饱和脂肪酸' },
  { name: '夏威夷果', alias: ['macadamia','xiaweiyi'], emoji: '🥜', category: '坚果', safety: 'ok', reason: '好吃但热量极高', tip: '每天几颗就好' },
  { name: '板栗', alias: ['chestnut','banli','栗子'], emoji: '🌰', category: '坚果', safety: 'good', reason: '补脾养胃，碳水较多' },
  { name: '南瓜子', alias: ['pumpkin seed','nanguazi'], emoji: '🌰', category: '坚果', safety: 'good', reason: '富含锌和镁' },
  { name: '葵花籽', alias: ['sunflower seed','kuihuazi','瓜子'], emoji: '🌻', category: '坚果', safety: 'ok', reason: '维E丰富但热量高盐重', tip: '选原味的，少量吃' },
  { name: '芝麻', alias: ['sesame','zhima','黑芝麻'], emoji: '🌰', category: '坚果', safety: 'good', reason: '补钙补铁，尤其黑芝麻' },
  { name: '碧根果', alias: ['pecan','bigenguo'], emoji: '🥜', category: '坚果', safety: 'good', reason: '不饱和脂肪酸和抗氧化物' },
  { name: '榛子', alias: ['hazelnut','zhenzi'], emoji: '🌰', category: '坚果', safety: 'good', reason: '维E含量很高' },

  // ==================== 油脂 (10+) ====================
  { name: '橄榄油', alias: ['olive oil','ganlanyou'], emoji: '🫒', category: '油脂', safety: 'good', reason: '单不饱和脂肪酸，地中海饮食核心', tip: '适合凉拌和低温烹饪' },
  { name: '菜籽油', alias: ['canola oil','caiziyou'], emoji: '🫗', category: '油脂', safety: 'ok', reason: '日常炒菜用油，还可以' },
  { name: '花生油', alias: ['peanut oil','huashengyou'], emoji: '🫗', category: '油脂', safety: 'ok', reason: '中国家庭常用油，可以用' },
  { name: '大豆油', alias: ['soybean oil','dadouyou'], emoji: '🫗', category: '油脂', safety: 'ok', reason: '日常用油，Omega-6偏高', tip: '可以混合使用不同油' },
  { name: '亚麻籽油', alias: ['flaxseed oil','yamaziyou'], emoji: '🫗', category: '油脂', safety: 'good', reason: 'Omega-3丰富，凉拌用' },
  { name: '芝麻油', alias: ['sesame oil','zhimayou','香油'], emoji: '🫗', category: '油脂', safety: 'ok', reason: '调味用，含抗氧化物' },
  { name: '椰子油', alias: ['coconut oil','yeziyou'], emoji: '🫗', category: '油脂', safety: 'ok', reason: '饱和脂肪高，少用', tip: '偶尔烘焙可以' },
  { name: '猪油', alias: ['lard','zhuyou'], emoji: '🫗', category: '油脂', safety: 'caution', reason: '饱和脂肪高，促进炎症' },
  { name: '黄油', alias: ['butter','huangyou'], emoji: '🧈', category: '油脂', safety: 'caution', reason: '饱和脂肪高', tip: '少量烘焙可以，不要大量使用' },
  { name: '人造黄油', alias: ['margarine','renzao'], emoji: '🧈', category: '油脂', safety: 'avoid', reason: '可能含反式脂肪酸，促炎' },

  // ==================== 调料 (25+) ====================
  { name: '姜黄', alias: ['turmeric','jianghuang'], emoji: '🟡', category: '调料', safety: 'good', reason: '姜黄素是天然抗炎明星', tip: '加点黑胡椒吸收更好' },
  { name: '食盐', alias: ['salt','yan','盐'], emoji: '🧂', category: '调料', safety: 'caution', reason: '高盐加重水肿和炎症', tip: '每天不超过5g，尽量少放' },
  { name: '酱油', alias: ['soy sauce','jiangyou'], emoji: '🫗', category: '调料', safety: 'ok', reason: '含盐较高，少放', tip: '选减盐酱油' },
  { name: '醋', alias: ['vinegar','cu','陈醋','米醋'], emoji: '🫗', category: '调料', safety: 'good', reason: '促进消化，有一定抗炎作用' },
  { name: '蚝油', alias: ['oyster sauce','haoyou'], emoji: '🫗', category: '调料', safety: 'ok', reason: '鲜味好但含盐高', tip: '少量调味用' },
  { name: '生抽', alias: ['light soy sauce','shengchou'], emoji: '🫗', category: '调料', safety: 'ok', reason: '比老抽盐少一些' },
  { name: '老抽', alias: ['dark soy sauce','laochou'], emoji: '🫗', category: '调料', safety: 'ok', reason: '上色用，少量即可' },
  { name: '味精', alias: ['MSG','weijing','鸡精'], emoji: '🧂', category: '调料', safety: 'ok', reason: '适量使用没有问题', tip: '可以减少盐的用量' },
  { name: '白糖', alias: ['sugar','baitang','砂糖'], emoji: '🧂', category: '调料', safety: 'caution', reason: '精制糖促进炎症', tip: '尽量少用' },
  { name: '冰糖', alias: ['rock sugar','bingtang'], emoji: '🧂', category: '调料', safety: 'ok', reason: '比白糖温和一些，煲汤少量用' },
  { name: '蜂蜜', alias: ['honey','fengmi'], emoji: '🍯', category: '调料', safety: 'ok', reason: '天然甜味剂，比白糖好' },
  { name: '黑胡椒', alias: ['black pepper','hujiao'], emoji: '🧂', category: '调料', safety: 'good', reason: '促进姜黄素吸收，有抗炎作用' },
  { name: '花椒', alias: ['Sichuan pepper','huajiao'], emoji: '🌶️', category: '调料', safety: 'ok', reason: '有一定抗炎成分', tip: '少量调味可以' },
  { name: '八角', alias: ['star anise','bajiao'], emoji: '⭐', category: '调料', safety: 'ok', reason: '炖肉常用香料，少量即可' },
  { name: '桂皮', alias: ['cinnamon','guipi','肉桂'], emoji: '🟤', category: '调料', safety: 'good', reason: '含抗炎成分，有助稳定血糖' },
  { name: '辣椒酱', alias: ['chili sauce','lajiaojiang','豆瓣酱'], emoji: '🌶️', category: '调料', safety: 'ok', reason: '发酵辣酱有一定益处', tip: '刺激肠胃，不宜过多' },
  { name: '番茄酱', alias: ['ketchup','fanqiejiang'], emoji: '🍅', category: '调料', safety: 'ok', reason: '含番茄红素，但加了糖和盐' },
  { name: '豆瓣酱', alias: ['doubanjiang','bean paste'], emoji: '🫗', category: '调料', safety: 'ok', reason: '发酵调料，盐分较高' },
  { name: '芝麻酱', alias: ['sesame paste','zhimajiang','麻酱'], emoji: '🥜', category: '调料', safety: 'ok', reason: '含钙和铁，热量较高' },
  { name: '沙拉酱', alias: ['mayonnaise','salad dressing','salajiang'], emoji: '🫗', category: '调料', safety: 'caution', reason: '高油高热量' },
  { name: '料酒', alias: ['cooking wine','liaojiu'], emoji: '🫗', category: '调料', safety: 'ok', reason: '做菜调味用，少量无妨' },
  { name: '米醋', alias: ['rice vinegar','micu'], emoji: '🫗', category: '调料', safety: 'good', reason: '酸度温和，促进消化' },
  { name: '腐乳', alias: ['fermented tofu','furu'], emoji: '🧈', category: '调料', safety: 'ok', reason: '发酵食品，但盐分很高', tip: '少量佐餐可以' },

  // ==================== 饮品 (25+) ====================
  { name: '绿茶', alias: ['green tea','lvcha'], emoji: '🍵', category: '饮品', safety: 'good', reason: '茶多酚抗氧化抗炎', tip: '不要喝太浓，下午3点后少喝避免影响睡眠' },
  { name: '白开水', alias: ['温水','水','water','shui'], emoji: '💧', category: '饮品', safety: 'good', reason: '最好的饮品！每天至少1.5L' },
  { name: '咖啡', alias: ['coffee','kafei'], emoji: '☕', category: '饮品', safety: 'ok', reason: '适量可以，每天不超过2杯', tip: '不要空腹喝，服药前后1小时避免' },
  { name: '奶茶', alias: ['milk tea','naicha'], emoji: '🧋', category: '饮品', safety: 'caution', reason: '高糖高热量，偶尔解馋', tip: '选少糖或无糖，不要天天喝' },
  { name: '可乐', alias: ['cola','kele','碳酸饮料','coke','百事'], emoji: '🥤', category: '饮品', safety: 'caution', reason: '高糖+磷酸影响钙吸收', tip: '偶尔喝一口可以，别当水喝' },
  { name: '酒', alias: ['啤酒','白酒','红酒','wine','beer','alcohol','jiu'], emoji: '🍷', category: '饮品', safety: 'caution', reason: '可能与羟氯喹相互作用，加重肝脏负担', tip: '如果要喝，每天不超过一小杯红酒' },
  { name: '蜂蜜水', alias: ['honey water','fengmishui'], emoji: '🍯', category: '饮品', safety: 'ok', reason: '天然甜味剂，比白糖好' },
  { name: '红茶', alias: ['black tea','hongcha'], emoji: '🍵', category: '饮品', safety: 'ok', reason: '含茶多酚，但发酵后减少', tip: '适量饮用' },
  { name: '菊花茶', alias: ['chrysanthemum tea','juhuacha'], emoji: '🍵', category: '饮品', safety: 'good', reason: '清肝明目，适合日常饮用' },
  { name: '枸杞茶', alias: ['goji tea','gouqicha'], emoji: '🍵', category: '饮品', safety: 'ok', reason: '抗氧化，但免疫增强效果要注意', tip: 'UCTD不要大量喝' },
  { name: '玫瑰花茶', alias: ['rose tea','meiguicha'], emoji: '🌹', category: '饮品', safety: 'good', reason: '疏肝理气，温和好喝' },
  { name: '柠檬水', alias: ['lemon water','ningmengshui'], emoji: '🍋', category: '饮品', safety: 'good', reason: '维C+补水，日常好饮品' },
  { name: '椰子水', alias: ['coconut water','yezishui'], emoji: '🥥', category: '饮品', safety: 'good', reason: '天然电解质，补水好选择' },
  { name: '橙汁', alias: ['orange juice','chengzhi'], emoji: '🍊', category: '饮品', safety: 'ok', reason: '维C丰富但糖分高', tip: '鲜榨比瓶装好，少量喝' },
  { name: '苹果醋', alias: ['apple cider vinegar','pingguocu'], emoji: '🍎', category: '饮品', safety: 'ok', reason: '有助消化', tip: '一定要稀释后喝' },
  { name: '豆浆', alias: ['soy milk','doujiang'], emoji: '🥛', category: '饮品', safety: 'ok', reason: '植物蛋白，适量饮用' },
  { name: '杏仁露', alias: ['almond milk','xingrenlu'], emoji: '🥛', category: '饮品', safety: 'ok', reason: '植物奶替代品，注意含糖量' },
  { name: '功能饮料', alias: ['energy drink','红牛','monster'], emoji: '🥤', category: '饮品', safety: 'caution', reason: '咖啡因和糖分过高', tip: '不建议经常喝' },
  { name: '雪碧', alias: ['sprite','xuebi'], emoji: '🥤', category: '饮品', safety: 'caution', reason: '高糖碳酸饮料' },
  { name: '果茶', alias: ['fruit tea','guocha'], emoji: '🧋', category: '饮品', safety: 'ok', reason: '比纯奶茶好一些，但注意糖分' },
  { name: '普洱茶', alias: ['puer tea','puercha'], emoji: '🍵', category: '饮品', safety: 'good', reason: '发酵茶，暖胃助消化' },
  { name: '乌龙茶', alias: ['oolong tea','wulongcha'], emoji: '🍵', category: '饮品', safety: 'good', reason: '半发酵茶，含茶多酚' },
  { name: '姜茶', alias: ['ginger tea','jiangcha'], emoji: '🫚', category: '饮品', safety: 'good', reason: '暖胃驱寒抗炎', tip: '关节痛的时候喝特别好' },
  { name: '红枣茶', alias: ['date tea','hongzaocha'], emoji: '🍵', category: '饮品', safety: 'good', reason: '补血养气，暖身' },

  // ==================== 零食甜品 (30+) ====================
  { name: '黑巧克力', alias: ['dark chocolate','heiqiaokeli'], emoji: '🍫', category: '零食', safety: 'ok', reason: '70%以上可可含量的有抗氧化作用', tip: '每天一小块（20g左右）' },
  { name: '蛋糕', alias: ['cake','dangao'], emoji: '🍰', category: '零食', safety: 'caution', reason: '高糖高脂，促进炎症', tip: '特殊日子吃一块没关系' },
  { name: '饼干', alias: ['cookie','binggan','曲奇'], emoji: '🍪', category: '零食', safety: 'caution', reason: '高糖+反式脂肪', tip: '选全麦少糖的品种' },
  { name: '薯片', alias: ['chips','shupian','乐事','品客'], emoji: '🍟', category: '零食', safety: 'caution', reason: '高盐高油，促进炎症' },
  { name: '冰淇淋', alias: ['ice cream','bingqilin','雪糕'], emoji: '🍦', category: '零食', safety: 'caution', reason: '高糖高脂', tip: '偶尔吃一个没关系，别天天吃' },
  { name: '坚果棒', alias: ['nut bar','jianguobang','能量棒'], emoji: '🥜', category: '零食', safety: 'ok', reason: '比薯片好的零食选择', tip: '注意看含糖量' },
  { name: '红枣', alias: ['大枣','date','hongzao'], emoji: '🫘', category: '零食', safety: 'good', reason: '补血养气，天然甜味' },
  { name: '枸杞', alias: ['goji','gouqi'], emoji: '🔴', category: '零食', safety: 'ok', reason: '抗氧化，但可能增强免疫', tip: 'UCTD患者适量食用，不要大量吃（免疫增强可能是双刃剑）' },
  { name: '糖果', alias: ['candy','tangguo','糖'], emoji: '🍬', category: '零食', safety: 'caution', reason: '纯糖，促进炎症，无营养' },
  { name: '面包干', alias: ['rusk','mianbaogan','吐司干'], emoji: '🍞', category: '零食', safety: 'ok', reason: '比薯片健康些的小零食' },
  { name: '果脯', alias: ['dried fruit','guopu','蜜饯','话梅'], emoji: '🍬', category: '零食', safety: 'caution', reason: '高糖+防腐剂', tip: '不如直接吃新鲜水果' },
  { name: '葡萄干', alias: ['raisin','putaogan'], emoji: '🫐', category: '零食', safety: 'ok', reason: '含铁和花青素，但糖分高', tip: '每次一小把就好' },
  { name: '蔓越莓干', alias: ['dried cranberry','manyuemeigan'], emoji: '🫐', category: '零食', safety: 'ok', reason: '抗氧化，但通常加了很多糖' },
  { name: '海苔', alias: ['nori','haitai','紫菜'], emoji: '🌿', category: '零食', safety: 'good', reason: '低热量，富含碘和矿物质', tip: '调味海苔注意盐分' },
  { name: '酸奶果粒', alias: ['yogurt granola','suannai'], emoji: '🥛', category: '零食', safety: 'ok', reason: '比纯零食好，但注意糖分' },
  { name: '豆干', alias: ['dried tofu snack','dougan'], emoji: '🧈', category: '零食', safety: 'ok', reason: '高蛋白零食', tip: '选低盐的' },
  { name: '牛肉干', alias: ['beef jerky','niurougan'], emoji: '🥩', category: '零食', safety: 'ok', reason: '高蛋白零食，但盐分较高' },
  { name: '月饼', alias: ['mooncake','yuebing'], emoji: '🥮', category: '零食', safety: 'caution', reason: '高糖高脂高热量', tip: '中秋吃一小块品尝就好' },
  { name: '元宵', alias: ['汤圆','glutinous rice ball','yuanxiao','tangyuan'], emoji: '🍡', category: '零食', safety: 'ok', reason: '糯米制品，不易消化', tip: '一次3-4个即可' },
  { name: '绿豆糕', alias: ['mung bean cake','lvdougao'], emoji: '🍡', category: '零食', safety: 'ok', reason: '含绿豆但糖分不低' },
  { name: '驴打滚', alias: ['donkey roll','lvdagun'], emoji: '🍡', category: '零食', safety: 'ok', reason: '传统点心，糖分和热量较高' },
  { name: '糯米糍', alias: ['mochi','nuomici','麻薯'], emoji: '🍡', category: '零食', safety: 'ok', reason: '糯米制品，适量吃' },
  { name: '膨化食品', alias: ['puffed snack','penghua','虾条','妙脆角'], emoji: '🍟', category: '零食', safety: 'caution', reason: '营养价值低，高盐高油' },
  { name: '辣条', alias: ['spicy strip','latiao'], emoji: '🌶️', category: '零食', safety: 'caution', reason: '高盐高油+添加剂多', tip: '不建议经常吃' },
  { name: '果冻', alias: ['jelly','guodong'], emoji: '🍮', category: '零食', safety: 'ok', reason: '热量不高但营养也没有' },
  { name: '巧克力', alias: ['chocolate','qiaokeli','牛奶巧克力'], emoji: '🍫', category: '零食', safety: 'ok', reason: '牛奶巧克力含糖高', tip: '选70%以上黑巧更好' },
  { name: '棉花糖', alias: ['marshmallow','mianhuatang'], emoji: '🍬', category: '零食', safety: 'caution', reason: '纯糖，没有任何营养' },

  // ==================== 加工食品 (20+) ====================
  { name: '罐头', alias: ['canned food','guantou'], emoji: '🥫', category: '加工', safety: 'caution', reason: '高盐高糖+防腐剂' },
  { name: '腌菜', alias: ['泡菜','咸菜','pickles','yancai'], emoji: '🥒', category: '加工', safety: 'caution', reason: '高盐，长期吃加重水肿' },
  { name: '速冻饺子', alias: ['frozen dumpling','sudong'], emoji: '🥟', category: '加工', safety: 'ok', reason: '偶尔吃方便', tip: '不如自己包的新鲜饺子' },
  { name: '外卖', alias: ['快餐','fast food','waimai'], emoji: '🥡', category: '加工', safety: 'caution', reason: '普遍高油高盐，不知道用什么油', tip: '偶尔吃可以，尽量选清淡的菜' },
  { name: '火锅', alias: ['hotpot','huoguo'], emoji: '🍲', category: '加工', safety: 'ok', reason: '底料高油高盐', tip: '选清汤锅底，多涮蔬菜和鱼肉' },
  { name: '烧烤', alias: ['BBQ','shaokao','撸串'], emoji: '🍖', category: '加工', safety: 'caution', reason: '高温烤制产生致癌物+高盐', tip: '偶尔吃，避免烤焦的部分' },
  { name: '麻辣烫', alias: ['malatang','spicy soup'], emoji: '🍲', category: '加工', safety: 'ok', reason: '汤底油大盐多', tip: '多选蔬菜和豆腐，少喝汤' },
  { name: '酸辣粉', alias: ['hot and sour noodle','suanlafen'], emoji: '🍜', category: '加工', safety: 'caution', reason: '高盐高油+淀粉' },
  { name: '炸鸡', alias: ['fried chicken','zhaji','肯德基','KFC'], emoji: '🍗', category: '加工', safety: 'caution', reason: '油炸食品，反复用油促炎', tip: '偶尔解馋一次' },
  { name: '汉堡', alias: ['hamburger','hanbao','麦当劳','McDonald'], emoji: '🍔', category: '加工', safety: 'caution', reason: '快餐，高脂高盐' },
  { name: '炸薯条', alias: ['french fries','shutiao'], emoji: '🍟', category: '加工', safety: 'caution', reason: '油炸+高盐' },
  { name: '披萨', alias: ['pizza','pisa'], emoji: '🍕', category: '加工', safety: 'ok', reason: '看配料而定，蔬菜多的好一些', tip: '薄底蔬菜披萨相对好' },
  { name: '寿司', alias: ['sushi','shousi'], emoji: '🍣', category: '加工', safety: 'ok', reason: '鱼生+米饭，还不错', tip: '注意新鲜度，孕期/免疫低避免生食' },
  { name: '拉面', alias: ['ramen','lamian'], emoji: '🍜', category: '加工', safety: 'ok', reason: '汤头往往高盐高脂', tip: '少喝汤' },
  { name: '煎饼果子', alias: ['jianbing','Chinese crepe'], emoji: '🫓', category: '加工', safety: 'ok', reason: '早餐选择，油不多还好' },
  { name: '小笼包', alias: ['soup dumpling','xiaolongbao'], emoji: '🥟', category: '加工', safety: 'ok', reason: '比油炸食品健康，蒸制' },
  { name: '酱牛肉', alias: ['braised beef','jiangniurou'], emoji: '🥩', category: '加工', safety: 'ok', reason: '高蛋白，注意盐分' },
  { name: '卤味', alias: ['braised food','luwei','卤鸡爪','卤鸭脖'], emoji: '🍗', category: '加工', safety: 'ok', reason: '卤制品含盐较多', tip: '偶尔吃一些可以' },
  { name: '臭豆腐', alias: ['stinky tofu','choudoufu'], emoji: '🧈', category: '加工', safety: 'caution', reason: '通常油炸，高油高盐' },
  { name: '串串香', alias: ['skewer hotpot','chuanchuan'], emoji: '🍢', category: '加工', safety: 'ok', reason: '类似火锅，选清汤底', tip: '多选蔬菜和菌类' },
  { name: '肉松', alias: ['pork floss','rousong'], emoji: '🥩', category: '加工', safety: 'ok', reason: '加工肉制品，少量佐餐' },
  { name: '泡面', alias: ['instant noodle','paomian','方便面'], emoji: '🍜', category: '加工', safety: 'caution', reason: '高盐高油，营养单一' },

  // ==================== 保健品 (15+) ====================
  { name: '鱼油', alias: ['fish oil','yuyou','omega3','DHA'], emoji: '💊', category: '保健品', safety: 'good', reason: 'Omega-3补充剂，抗炎', tip: '选EPA+DHA含量高的品牌' },
  { name: '维生素D', alias: ['vitamin D','weishengsuD','VD'], emoji: '💊', category: '保健品', safety: 'good', reason: '羟氯喹长期服用可能需要补充', tip: '建议查血后在医生指导下补充' },
  { name: '钙片', alias: ['calcium','gaipian'], emoji: '💊', category: '保健品', safety: 'ok', reason: '长期服药需要关注骨密度', tip: '食补优先，不够再吃钙片' },
  { name: '维生素C', alias: ['vitamin C','weishengsuC','VC'], emoji: '💊', category: '保健品', safety: 'ok', reason: '抗氧化，适量补充', tip: '食物中获取最好，不要过量' },
  { name: '维生素E', alias: ['vitamin E','weishengsuE','VE'], emoji: '💊', category: '保健品', safety: 'ok', reason: '抗氧化保护细胞', tip: '坚果中也含丰富维E' },
  { name: '维生素B族', alias: ['vitamin B','weishengsuB','B12','叶酸'], emoji: '💊', category: '保健品', safety: 'ok', reason: '支持神经系统和能量代谢' },
  { name: '益生菌', alias: ['probiotics','yishengjun'], emoji: '💊', category: '保健品', safety: 'ok', reason: '肠道健康很重要', tip: '选知名品牌' },
  { name: '胶原蛋白', alias: ['collagen','jiaoyuandanbai'], emoji: '💊', category: '保健品', safety: 'ok', reason: '对皮肤和关节可能有帮助' },
  { name: '辅酶Q10', alias: ['CoQ10','coenzyme Q10','fumeiq10'], emoji: '💊', category: '保健品', safety: 'ok', reason: '抗氧化，保护心脏', tip: '服药期间先咨询医生' },
  { name: '葡萄籽', alias: ['grape seed','putaozi','OPC'], emoji: '💊', category: '保健品', safety: 'ok', reason: '原花青素抗氧化', tip: '适量补充' },
  { name: '褪黑素', alias: ['melatonin','tuiheisu'], emoji: '💊', category: '保健品', safety: 'ok', reason: '帮助睡眠', tip: '短期使用，不要长期依赖' },
  { name: '苜蓿补充剂', alias: ['alfalfa supplement','muxu'], emoji: '💊', category: '保健品', safety: 'avoid', reason: '严禁！任何含苜蓿成分的保健品都不能吃' },
  { name: '紫锥菊', alias: ['echinacea','zizhuiju'], emoji: '💊', category: '保健品', safety: 'avoid', reason: '免疫增强剂，可能刺激自身免疫', tip: '所有「增强免疫力」的保健品都要谨慎' },
  { name: '灵芝', alias: ['reishi','lingzhi'], emoji: '🍄', category: '保健品', safety: 'caution', reason: '免疫调节作用，UCTD需谨慎', tip: '不建议自行服用，先咨询医生' },
  { name: '人参', alias: ['ginseng','renshen'], emoji: '🌿', category: '保健品', safety: 'caution', reason: '免疫增强，UCTD不宜自行服用', tip: '一定要在医生指导下使用' },
  { name: '冬虫夏草', alias: ['cordyceps','dongchongxiacao'], emoji: '🌿', category: '保健品', safety: 'caution', reason: '免疫调节作用不明确，价格虚高', tip: 'UCTD患者不建议自行服用' },
  { name: '蜂王浆', alias: ['royal jelly','fengwangjiang'], emoji: '🍯', category: '保健品', safety: 'caution', reason: '含激素类物质，自身免疫病需谨慎' },
  { name: '螺旋藻', alias: ['spirulina','luoxuanzao'], emoji: '🌿', category: '保健品', safety: 'caution', reason: '可能激活免疫系统', tip: 'UCTD/狼疮患者应避免' },

  // ==================== 常见中式菜品 (30+) ====================
  { name: '清蒸鱼', alias: ['steamed fish','qingzhengyu'], emoji: '🐟', category: '菜品', safety: 'good', reason: '最健康的鱼类烹饪方式，少油少盐' },
  { name: '水煮菜', alias: ['boiled vegetables','shuizhucai'], emoji: '🥬', category: '菜品', safety: 'good', reason: '低脂低盐，减脂好选择' },
  { name: '白灼虾', alias: ['blanched shrimp','baizhuoxia'], emoji: '🦐', category: '菜品', safety: 'ok', reason: '简单健康的虾类做法', tip: '不过敏就可以吃' },
  { name: '蒸蛋', alias: ['steamed egg','zhengdan','鸡蛋羹'], emoji: '🥚', category: '菜品', safety: 'good', reason: '嫩滑易消化，营养全面' },
  { name: '炒时蔬', alias: ['stir-fried vegetables','chaoshishu'], emoji: '🥬', category: '菜品', safety: 'good', reason: '日常蔬菜少油炒即可' },
  { name: '番茄炒蛋', alias: ['tomato egg','fanqiechaidan'], emoji: '🍅', category: '菜品', safety: 'ok', reason: '国民家常菜，番茄煮熟更好' },
  { name: '西兰花炒虾仁', alias: ['broccoli shrimp','xilanhuachaxiaren'], emoji: '🥦', category: '菜品', safety: 'good', reason: '高蛋白+抗炎蔬菜，很好的搭配' },
  { name: '鸡汤', alias: ['chicken soup','jitang'], emoji: '🍲', category: '菜品', safety: 'good', reason: '温补养生，含胶原蛋白', tip: '去掉浮油更健康' },
  { name: '骨头汤', alias: ['bone broth','gutoutang'], emoji: '🍲', category: '菜品', safety: 'ok', reason: '补钙效果其实不大，但暖胃', tip: '去浮油，别加太多盐' },
  { name: '银耳羹', alias: ['white fungus soup','yinergeng'], emoji: '🍲', category: '菜品', safety: 'good', reason: '润肺养颜，少糖更好' },
  { name: '小米粥', alias: ['millet porridge','xiaomizhou'], emoji: '🥣', category: '菜品', safety: 'good', reason: '养胃首选，温和易消化' },
  { name: '山药排骨汤', alias: ['yam pork rib soup','shanyaopaigutang'], emoji: '🍲', category: '菜品', safety: 'good', reason: '补脾养胃的好汤' },
  { name: '蔬菜沙拉', alias: ['salad','shucaisala'], emoji: '🥗', category: '菜品', safety: 'good', reason: '新鲜蔬菜组合，抗氧化', tip: '选橄榄油醋汁，避免高脂沙拉酱' },
  { name: '红烧肉', alias: ['braised pork','hongshaorou'], emoji: '🍖', category: '菜品', safety: 'caution', reason: '高脂高糖高盐', tip: '偶尔解馋吃两块' },
  { name: '水煮鱼', alias: ['boiled fish','shuizhuyu'], emoji: '🐟', category: '菜品', safety: 'caution', reason: '虽然是鱼但油非常多', tip: '不是真的"水"煮的' },
  { name: '麻婆豆腐', alias: ['mapo tofu','mapodoufu'], emoji: '🧈', category: '菜品', safety: 'ok', reason: '豆腐不错，但油盐较多' },
  { name: '回锅肉', alias: ['twice-cooked pork','huiguorou'], emoji: '🥩', category: '菜品', safety: 'caution', reason: '高脂肪，肥肉为主' },
  { name: '宫保鸡丁', alias: ['kung pao chicken','gongbaojiding'], emoji: '🍗', category: '菜品', safety: 'ok', reason: '鸡肉+花生，中等油量' },
  { name: '鱼香肉丝', alias: ['yuxiang shredded pork','yuxiangrousi'], emoji: '🥩', category: '菜品', safety: 'ok', reason: '家常菜，盐糖油适中' },
  { name: '清炒豆角', alias: ['stir-fried green beans','qingchaodoujiao'], emoji: '🫛', category: '菜品', safety: 'good', reason: '日常蔬菜，简单健康', tip: '豆角一定要炒熟' },
  { name: '紫菜蛋花汤', alias: ['seaweed egg soup','zicaidanhuatang'], emoji: '🍲', category: '菜品', safety: 'good', reason: '简单清淡又营养' },
  { name: '冬瓜排骨汤', alias: ['winter melon soup','dongguapaigutang'], emoji: '🍲', category: '菜品', safety: 'good', reason: '清淡利湿好汤' },
  { name: '糖醋排骨', alias: ['sweet sour ribs','tangcupaigu'], emoji: '🍖', category: '菜品', safety: 'ok', reason: '糖和油较多，但骨头有钙', tip: '偶尔吃' },
  { name: '蒜蓉西兰花', alias: ['garlic broccoli','suanrongxilanhua'], emoji: '🥦', category: '菜品', safety: 'good', reason: '蒜+西兰花，双重抗炎' },
  { name: '莲藕排骨汤', alias: ['lotus root pork rib soup','lianoupaigutang'], emoji: '🍲', category: '菜品', safety: 'good', reason: '养胃好汤，秋冬适合' },
  { name: '凉拌黄瓜', alias: ['smashed cucumber','liangbanhuanggua'], emoji: '🥒', category: '菜品', safety: 'good', reason: '清爽低热量，夏天好菜' },
  { name: '蒸南瓜', alias: ['steamed pumpkin','zhengnangua'], emoji: '🎃', category: '菜品', safety: 'good', reason: '甜甜软软，当主食或菜都行' },
  { name: '酸菜鱼', alias: ['sour cabbage fish','suancaiyu'], emoji: '🐟', category: '菜品', safety: 'ok', reason: '鱼不错但汤底油盐重', tip: '少喝汤' },
  { name: '干锅', alias: ['dry pot','ganguo'], emoji: '🍳', category: '菜品', safety: 'caution', reason: '油量很大' },
  { name: '红烧茄子', alias: ['braised eggplant','hongshaoquiezi'], emoji: '🍆', category: '菜品', safety: 'ok', reason: '茄子吸油很多', tip: '蒸茄子更健康' },
];

// Category info for display
export const FOOD_CATEGORIES = [
  { key: '蔬菜', emoji: '🥬' },
  { key: '水果', emoji: '🍎' },
  { key: '肉蛋', emoji: '🥩' },
  { key: '主食', emoji: '🍚' },
  { key: '豆类', emoji: '🫘' },
  { key: '乳制品', emoji: '🥛' },
  { key: '坚果', emoji: '🥜' },
  { key: '油脂', emoji: '🫗' },
  { key: '调料', emoji: '🧂' },
  { key: '饮品', emoji: '🍵' },
  { key: '零食', emoji: '🍬' },
  { key: '加工', emoji: '🥫' },
  { key: '菜品', emoji: '🍳' },
  { key: '保健品', emoji: '💊' },
];

export const SAFETY_INFO = {
  good:    { label: '推荐', color: '#10b981', bg: '#ecfdf5', border: '#a7f3d0', emoji: '✅' },
  ok:      { label: '适量', color: '#3b82f6', bg: '#eff6ff', border: '#bfdbfe', emoji: '👌' },
  caution: { label: '少吃', color: '#f59e0b', bg: '#fffbeb', border: '#fde68a', emoji: '⚠️' },
  avoid:   { label: '避免', color: '#ef4444', bg: '#fef2f2', border: '#fecaca', emoji: '🚫' },
};

/**
 * Simple fuzzy search - matches name and aliases
 * Supports partial match, case insensitive
 */
export function searchFood(query: string): FoodItem[] {
  if (!query.trim()) return [];
  const q = query.toLowerCase().trim();

  return FOOD_DATABASE.filter((food) => {
    if (food.name.toLowerCase().includes(q)) return true;
    if (food.alias?.some((a) => a.toLowerCase().includes(q))) return true;
    if (food.category.includes(q)) return true;
    if (food.reason.includes(q)) return true;
    return false;
  }).sort((a, b) => {
    // Exact name match first
    const aExact = a.name.toLowerCase().startsWith(q) ? 0 : 1;
    const bExact = b.name.toLowerCase().startsWith(q) ? 0 : 1;
    if (aExact !== bExact) return aExact - bExact;
    // Then by safety level importance
    const order = { avoid: 0, caution: 1, ok: 2, good: 3 };
    return order[a.safety] - order[b.safety];
  });
}
